#!/usr/bin/env bash
# This script is based on ThePrimeagen's tmux-sessionizer bash script

if [[ -z $TMS_PJ_DIRS ]]; then
    TMS_PJ_DIRS="./"
fi

if [[ $# -eq 1 ]]; then
    selected=$(realpath $1)
else
    selected=$(find $TMS_PJ_DIRS -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

name_length=$(expr ${#selected_name} + 2) 
if [[ $name_length -gt $(tmux show-option -gqv status-left-length) ]]; then
    tmux set-option -t "$selected_name" status-left-length "$name_length"
fi

tmux switch-client -t $selected_name
